// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdrvowacecxnraaivlhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcnZvd2FjZWN4bnJhYWl2bGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMzE1MjMsImV4cCI6MjA3OTYwNzUyM30.J67LWVWT51CdEFxiKVOE4QhGnu6KbYgH2XM0IHl3vsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});